name: Get core/driver versions from CDI/FDI version
description: Get core/driver versions from CDI/FDI version
author: Supertokens

# # Add your action's branding here. This will appear on the GitHub Marketplace.
# branding:
#   icon: heart
#   color: red

inputs:
  driver-name:
    description: The driver being used for the code
    required: true

  cdi-version:
    description: CDI Version to use
    required: false
    default: ''

  core-plan-type:
    description: The plan for the supertokens core
    required: false
    default: FREE

  core-mode:
    description: The mode for the supertokens core
    required: false
    default: DEV

  fdi-version:
    description: FDI Version to use
    required: false
    default: ''

  frontend-mode:
    description: The mode for the frontend
    required: false
    default: DEV

outputs:
  coreVersionXy:
    description: Supertokens-core version corresponding to CDI version
  coreTag:
    description: ''
  coreVersion:
    description: ''

  pluginInterfaceVersionXy:
    description: ''
  pluginInterfaceTag:
    description: ''
  pluginInterfacVersion:
    description: ''

  frontendVersionXy:
    description: ''
  frontendTag:
    description: ''
  frontendVersion:
    description: ''

  nodeVersionXy:
    description: ''
  nodeTag:
    description: ''

  authReactVersionXy:
    description: ''
  authReactTag:
    description: ''
  authReactVersion:
    description: ''

runs:
  using: node20
  main: dist/index.js
